# Numpy

NumPy is a powerful Python library for numerical computing

Numpy is a linear algebra library, mathematical operations on large amount of data

Gives multidimesnional array

nd array

1d 
2d 
3d


We have lists, but 

Advantags
- memory requirements (less memory
- Faster 
- convinence
- functionality


In [9]:
import numpy as np
import sys

li_arr = [i for i in range(100)]     # Create list of 100 elements
np_arr = np.arange(100)              # Create numpy array of 100 elements

print(li_arr)
print(np_arr)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [13]:
print("Np",np_arr.itemsize,"Bytes for 1 value")
## Size of 100 elements in numpy array
print(np_arr.itemsize * np_arr.size)


Np 4 Bytes for 1 value
400


In [12]:

print("List",sys.getsizeof(1),"Bytes for 1 value")
## Size of 100 elements in python list
print(sys.getsizeof(1) * len(li_arr))

List 28 Bytes for 1 value
2800


## Time Execution
NumPy arrays are much faster as compared to python list. We can easily verify this

In [22]:
import time
import numpy as np  

size = 100000


def addition_using_list():
  t1 = time.time() #starts after epoch
  a = range(size)
  b = range(size)
  c = [a[i] + b[i] for i in range(size)]
  t2 = time.time()
  return t2 - t1
  
def addition_using_numpy():
  t1 = time.time()
  a = np.arange(size)
  b = np.arange(size)
  c = a + b
  t2 = time.time()
  return t2 - t1


t_list = addition_using_list()
t_numpy = addition_using_numpy()
print("List = ", t_list * 1000, "milli seconds")   
print("NumPy = ", t_numpy * 1000,"milli seconds")

List =  20.943403244018555 milli seconds
NumPy =  0.9999275207519531 milli seconds


In [19]:
a= range(100)
a[7]

7

In [20]:
a = np.arange(size)
a

array([    0,     1,     2, ..., 99997, 99998, 99999])

why numpy is faster

for lists a,b we go size iterations

in case of numpy task is performed in chunks rather elements by elements

in two iterations
1 iteration half task completed
2 iteration half task completed 

This process is called vectorization

The numpy library is written very optimized manner in c languge and fortan language,

a+b

we have speed and ease of use

In [24]:
import numpy as np
# np is alias

a=[1,2,3]
b=np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [25]:
import numpy as np
# np is alias

a=[1,2,3,"5",True,4.5]
b=np.array(a)
print(b)
print(type(b))

['1' '2' '3' '5' 'True' '4.5']
<class 'numpy.ndarray'>


In [27]:
# numpy contains only homogenous
# to overcome we use dtype =int,float,str

import numpy as np
# np is alias

a=[1,2,3,"5",True,4.5]
b=np.array(a,dtype=int) #type casting the values should be like they can be converted
print(b)
print(type(b))

[1 2 3 5 1 4]
<class 'numpy.ndarray'>


In [28]:
# numpy contains only homogenous
# to overcome we use dtype =int,float,str

import numpy as np
# np is alias

a=[1,2,3,"5",True,4.5]
b=np.array(a,dtype=float) #type casting the values should be like they can be converted
print(b)
print(type(b))

[1.  2.  3.  5.  1.  4.5]
<class 'numpy.ndarray'>


In [29]:
# numpy contains only homogenous
# to overcome we use dtype =int,float,str

import numpy as np
# np is alias

a=[1,2,3,"5",True,4.5]
b=np.array(a,dtype=str) #type casting the values should be like they can be converted
print(b)
print(type(b))

['1' '2' '3' '5' 'True' '4.5']
<class 'numpy.ndarray'>


In [30]:
# numpy contains only homogenous
# to overcome we use dtype =int,float,str

import numpy as np
# np is alias

a=[1,2,3,"5",True,4.5]
b=np.array(a*3) #type casting the values should be like they can be converted
print(b)
print(type(b))

['1' '2' '3' '5' 'True' '4.5' '1' '2' '3' '5' 'True' '4.5' '1' '2' '3' '5'
 'True' '4.5']
<class 'numpy.ndarray'>


In [31]:
 # There are few more, they np.ones(), np.zeroes(), np.full(), np.empty()

In [32]:
 np.ones(3,dtype=int) #default is float

array([1, 1, 1])

In [36]:
 np.ones((2,3),dtype=int) #default is float

array([[1, 1, 1],
       [1, 1, 1]])

In [34]:
 np.zeros(3,dtype=int) #default is float

array([0, 0, 0])

In [38]:
 np.zeros((2,6),dtype=int) #default is float

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [39]:
 np.full(3) #dimension size and fill value should be passed

TypeError: full() missing 1 required positional argument: 'fill_value'

In [40]:
 np.full(3) #dimension size and fill value should be passed
# default is int

TypeError: full() missing 1 required positional argument: 'fill_value'

In [42]:
 np.full(3,4) #dimension size and fill value should be passed
# default is int

array([4, 4, 4])

In [43]:
 np.full((2,3),4)

array([[4, 4, 4],
       [4, 4, 4]])

In [44]:
list =[[1,2,3],[4,5,6],[7,8,9]]

np.array(list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
narr= np.zeros(10,dtype=int) #dtype = data type

In [47]:
narr[4]=1

In [48]:
narr

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [50]:
b=np.arange(10) #by default start=0, step=1
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
b=np.arange(2,10) #by default start=0, step=1
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
b=np.arange(2,10,2) #by default start=0, step=1
b

array([2, 4, 6, 8])

In [54]:
c= np.linspace(0,10,60) #start mandatoty and num is by default 50 samples
c

array([ 0.        ,  0.16949153,  0.33898305,  0.50847458,  0.6779661 ,
        0.84745763,  1.01694915,  1.18644068,  1.3559322 ,  1.52542373,
        1.69491525,  1.86440678,  2.03389831,  2.20338983,  2.37288136,
        2.54237288,  2.71186441,  2.88135593,  3.05084746,  3.22033898,
        3.38983051,  3.55932203,  3.72881356,  3.89830508,  4.06779661,
        4.23728814,  4.40677966,  4.57627119,  4.74576271,  4.91525424,
        5.08474576,  5.25423729,  5.42372881,  5.59322034,  5.76271186,
        5.93220339,  6.10169492,  6.27118644,  6.44067797,  6.61016949,
        6.77966102,  6.94915254,  7.11864407,  7.28813559,  7.45762712,
        7.62711864,  7.79661017,  7.96610169,  8.13559322,  8.30508475,
        8.47457627,  8.6440678 ,  8.81355932,  8.98305085,  9.15254237,
        9.3220339 ,  9.49152542,  9.66101695,  9.83050847, 10.        ])

In [55]:
c[1]-c[0]

0.1694915254237288

In [59]:
c= np.linspace(0,10,dtype =int) #start mandatoty and num is by default 50 samples (start and end are inclusive)
c # endpoint =False then end is exclusive

array([ 0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,
        3,  3,  3,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  6,  6,  6,  6,
        6,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9, 10])

In [58]:
c= np.linspace(0,10,dtype =int,endpoint=False) #start mandatoty and num is by default 50 samples (start and end are inclusive)
c # endpoint =False then end is exclusive

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4,
       4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8,
       8, 9, 9, 9, 9, 9])

In [60]:
# np.arange step value we choose
# np.linspace step is random 

In [62]:
np.identity(3) #identity matrix :one argument n

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
np.eye(3,4) #identity matrix :with rows*columns

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [65]:
b= np.random.rand(3)
b

array([0.82632373, 0.34814832, 0.17773364])

In [66]:
a= np.random.rand(2,3) 
a

array([[0.12446621, 0.71546247, 0.68132617],
       [0.94636923, 0.87171307, 0.93023891]])

In [69]:
a= np.random.rand(2,3)*10  # 0 to 1
a

array([[8.37323398, 9.47873159, 3.83422251],
       [1.63209552, 8.13909501, 4.88149459]])

In [73]:
a= np.random.randint(2,10) #btw the range 2,1)
a

8

In [74]:
a= np.array([0,1,2,3])
a.shape #dimension

(4,)

In [75]:
np.random.rand()

0.6765093773939854

In [76]:
np.random.rand(2,2)

array([[0.66844882, 0.35392658],
       [0.23938826, 0.31166242]])

In [78]:
a= np.random.randint(10,4) 
a

ValueError: low >= high

In [80]:
np.random.randint(10,size=(4,4))

array([[5, 2, 5, 0],
       [0, 6, 7, 8],
       [7, 6, 2, 1],
       [2, 7, 7, 4]])

In [81]:
np.arange(9,50)

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

In [83]:
np.eye(5,6,dtype=int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0]])

In [91]:
# Cut the rope
# 5m 9parts
f= 5/9

f= round(f,2)
print(f)
narr= np.arange(0,5,step=f)
narr


0.56


array([0.  , 0.56, 1.12, 1.68, 2.24, 2.8 , 3.36, 3.92, 4.48])

In [88]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    ``arange`` can be called with a varying number of positional arguments:
    
    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.
    
    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.
    
    S

### numpy
Numpy arrays are basically collection of references or collection of pointers which points to
4 different attributes

- data: reference to 1st byte of the array /1st element
- shape: shape/size of the array
- dtype- datatype of the array
- strides: no of bytes to skip to get next element of the array


In [92]:
import numpy as np

li=[1,2,3,4,5]

arr= np.array(li)

print(li)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [93]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)

(5,)
int32
(4,)


In [117]:
li_2d=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr_2d = np.array(li_2d)

print(li_2d)
print(arr_2d)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [118]:
print(arr_2d.data)
print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.strides) #rows,column

(4, 4)
int32
(16, 4)


In [119]:
# Acessing and slicing for 1d arrays of numpy is similar to lists
import numpy as np

li=[1,2,3,4,5]

arr= np.array(li)

print(li[0])
print(arr[0])
print(li[1:3])
print(arr[1:3])

1
1
[2, 3]
[2 3]


In [125]:
li_2d=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr_2d = np.array(li_2d)

print(li_2d[2][1])
print(arr_2d[2][1])
print(arr_2d[2,1]) #other syntax easy syntax

10
10
10


In [126]:
# slicing 2d list and 2d array
print(li_2d[1][0:3])
print(arr_2d[1,0:3])


[5, 6, 7]
[5 6 7]


In [127]:
x=li_2d[0:3]
print(x)
print(x[1])

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[5, 6, 7, 8]


In [128]:
# column fixed rows varing
print(li_2d[:2][1])
# print(arr_2d[1,0:3]) 
# in 2d list we cant acess 1 colum or column part directly like 2d arrays

[5, 6, 7, 8]


In [129]:
# column fixed rows varing
print(arr_2d[:3][1])
print(arr_2d[:3,1])


[5 6 7 8]
[ 2  6 10]


In [133]:
# part of array we can get
print(arr_2d[2:4][1:3])
print(arr_2d[2:4][1:3])
print(arr_2d[2:4,1:3])

[[13 14 15 16]]
[[13 14 15 16]]
[[10 11]
 [14 15]]


In [161]:
import numpy as np

li=[1,2,3,4,5]

a=np.random.randint(1,20,5)
b=np.random.randint(1,20,5)

print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[10 19  5  3  9]
[ 3 15  9  2  4]


In [162]:
 # increaseby 1 for each element
li=[i+1 for i in li]
li

[2, 3, 4, 5, 6]

In [163]:
# in case of numpy array
# in terms of computation , they are very fast

a=a+1
b=b+1
print(a)
print(b)

[11 20  6  4 10]
[ 4 16 10  3  5]


In [164]:
# c[i]=a[i]+b[i]
c=a+b
c

array([15, 36, 16,  7, 15])

In [165]:
d=a-b
d

array([ 7,  4, -4,  1,  5])

In [166]:
e=a/b
e

array([2.75      , 1.25      , 0.6       , 1.33333333, 2.        ])

In [167]:
f=a//b
f

array([2, 1, 0, 1, 2])

In [168]:
# a=[a,b,c,d]
# b=[i,j,k,l]
# h=[a^i,b^j,c^k,d^l]

g=a**b
g

array([   14641,        0, 60466176,       64,   100000])

In [169]:
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())
print(a.max())
print(a.argmax())

51
10.2
4
3
20
1


In [170]:
# Relational and logical
print(a)
print(b)

[11 20  6  4 10]
[ 4 16 10  3  5]


In [171]:
a>b

array([ True,  True, False,  True,  True])

In [172]:
a<b

array([False, False,  True, False, False])

In [173]:
a==b

array([False, False, False, False, False])

In [174]:
# logical
print(np.logical_or(a,b))
print(np.logical_and(a,b))
print(np.logical_not(a))

[ True  True  True  True  True]
[ True  True  True  True  True]
[False False False False False]


# Boolean indexing


In [179]:
print(b)
print(b>10)

[ 4 16 10  3  5]
[False  True False False False]


In [180]:
# extract elements greater than 10

bool_arr =b>5
print(bool_arr)

new_arr =b[bool_arr]
print(new_arr)

[False  True  True False False]
[16 10]


In [182]:
new_arr2 = b[b>1]
new_arr2

array([ 4, 16, 10,  3,  5])

In [184]:
new_arr2 = b[b>1 & b<10]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [186]:
new_arr2 = b[(b>1) & (b<10)]
new_arr2

array([4, 3, 5])

In [187]:
b

array([ 4, 16, 10,  3,  5])

In [188]:
c

array([15, 36, 16,  7, 15])

In [189]:
c[:3]=10

In [190]:
c

array([10, 10, 10,  7, 15])

In [193]:
c[c>10] =100

In [194]:
c

array([ 10,  10,  10,   7, 100])

In [195]:
a

array([11, 20,  6,  4, 10])

In [196]:
c

array([ 10,  10,  10,   7, 100])

In [198]:
print(c[c ==10])

[10 10 10]


In [199]:
# indexes array

ind = np.where(c==10)

In [200]:
ind

(array([0, 1, 2], dtype=int64),)

In [210]:
a= np.array(['t','b','r','d','e','f','z','a','w','y','y','h','t','j'])
print(len(a))
b= np.array([100,120,140,190,100,200,120,100,240,250,300,320,400,100])
print(len(b))
ind= np.where(b==100)
ind

14
14


(array([ 0,  4,  7, 13], dtype=int64),)

In [211]:
# if b[i]==100 then only print a[i]
print(a[ind]) #need same size 

['t' 'e' 'a' 'j']


In [216]:
a= np.array([0,120,0,190,100,0,120,100,0,250,0,0,400,0])

# extract non zero elements indexes
list= a[a>0]

print(list)
indexes= np.where(a>0)
print(indexes)
print(a[indexes])

[120 190 100 120 100 250 400]
(array([ 1,  3,  4,  6,  7,  9, 12], dtype=int64),)
[120 190 100 120 100 250 400]


In [222]:
a= np.array([i for i in range(1,30,2)])

print(a)
# list= a[a>0]

# print(list)

indexes= np.where(a%3==0)

print(indexes)
print(a[indexes])

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
(array([ 1,  4,  7, 10, 13], dtype=int64),)
[ 3  9 15 21 27]


In [223]:
a=np.array([i for i in range(1,11)])

# replace the odd numbers in numpy array with -1

indexes = np.where(a%2==1)

a[indexes]=-1

a

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

In [224]:
# replace the first occurence by 0

a= np.array([i for i in range(11,20)])

a[a.argmax()]=0

for i in a:
    print(i)


11
12
13
14
15
16
17
18
0


In [226]:
# negate nums btw 3,8 indexes
import numpy as np
arr = np.arange(1,11)
arr[2:8] = np.multiply(arr[2:8],-1)
for i in arr:
    print(i)

array([ 0,  1,  2, -1, -1, -1, -1, -1, -1,  9, 10, 11, 12, 13, 14])

In [227]:
ages=np.random.randint(15,18,20)
heights=np.random.randint(150,165,20)
print(ages)
print(heights)

[15 16 17 17 15 17 16 17 16 16 17 15 16 17 15 16 17 16 17 17]
[157 164 160 154 161 161 151 153 152 163 153 156 164 164 158 154 163 155
 157 155]


In [228]:
# print the age of students whose height is above 155

above_155 = heights>155

print(ages[above_155])

[15 16 17 15 17 16 15 16 17 15 17 17]


In [1]:
# Boolean Indexing for 2d array

import numpy as np

a=np.random.randint(1,30,(5,6))
print(a)

[[15 18 14 15 28  6]
 [ 7 24 16  3 18 27]
 [ 8 13 26 10  5 28]
 [23  5 24 13 24 29]
 [15 28  4 26 20 19]]


In [3]:
bool_arr=a>20

print(bool_arr)

[[False False False False  True False]
 [False  True False False False  True]
 [False False  True False False  True]
 [ True False  True False  True  True]
 [False  True False  True False False]]


In [4]:
ans=a[bool_arr] #bool_arr 

In [5]:
ans

array([28, 24, 27, 26, 28, 23, 24, 24, 29, 28, 26])

In [6]:
# f a[i][j]>20 then a[i][j] =20

a[a>20]=100
a

array([[ 15,  18,  14,  15, 100,   6],
       [  7, 100,  16,   3,  18, 100],
       [  8,  13, 100,  10,   5, 100],
       [100,   5, 100,  13, 100, 100],
       [ 15, 100,   4, 100,  20,  19]])

In [7]:
a

array([[ 15,  18,  14,  15, 100,   6],
       [  7, 100,  16,   3,  18, 100],
       [  8,  13, 100,  10,   5, 100],
       [100,   5, 100,  13, 100, 100],
       [ 15, 100,   4, 100,  20,  19]])

In [8]:
# for specific column
bool_arr =a[:,3] == 100
bool_arr

array([False, False, False, False,  True])

In [10]:
a[bool_arr,3]=99
a

array([[ 15,  18,  14,  15, 100,   6],
       [  7, 100,  16,   3,  18, 100],
       [  8,  13, 100,  10,   5, 100],
       [100,   5, 100,  13, 100, 100],
       [ 15, 100,   4,  99,  20,  19]])

In [12]:
# sort a given 2d array of shape (4,5) by 2nd column i.e column at index 1 in ascending
# That means, we should re arrange complete row based on 2nd column's values

array =np.random.randint(1,20,(4,5))

array

array([[ 2, 14,  6,  8, 17],
       [ 2,  5, 14,  7,  8],
       [15, 18,  6, 18,  8],
       [12, 16, 12, 15, 13]])

In [16]:
a= np.sort(array[:,1])

array([ 5, 14, 16, 18])

In [25]:
np.sort(array)
array

array([[ 2,  5,  6,  8, 17],
       [ 2,  7,  8, 14, 14],
       [ 6,  8, 15, 16, 18],
       [12, 12, 13, 15, 18]])

In [19]:
import numpy as np

# Sample 2D array (4x5)
# Replace this with your actual array
# For example:
# arr = np.array([[5, 9, 2, 8, 1],
#                 [7, 4, 3, 6, 0],
#                 [9, 2, 1, 5, 3],
#                 [3, 1, 4, 2, 8]])

arr = np.array([[5, 9, 2, 8, 1],
                [7, 4, 3, 6, 0],
                [9, 2, 1, 5, 3],
                [3, 1, 4, 2, 8]])

# Get the indices that would sort the array based on the 2nd column (index 1)
sort_indices = np.argsort(arr[:, 1])

print(sort_indices)
print(type(sort_indices))
# Rearrange the rows based on the sorted indices
sorted_arr = arr[sort_indices]

print("Original array:")
print(arr)

print("\nSorted array by 2nd column:")
print(sorted_arr)


[3 2 1 0]
<class 'numpy.ndarray'>
Original array:
[[5 9 2 8 1]
 [7 4 3 6 0]
 [9 2 1 5 3]
 [3 1 4 2 8]]

Sorted array by 2nd column:
[[3 1 4 2 8]
 [9 2 1 5 3]
 [7 4 3 6 0]
 [5 9 2 8 1]]


In [28]:
import numpy as np

x= np.random.randint(1,10,(3,3))
y= np.random.randint(1,10,(3,3))
print(x)
print()
print(y)

[[6 5 4]
 [9 6 6]
 [6 5 5]]

[[6 9 8]
 [4 2 4]
 [9 4 2]]


In [29]:
ans = x+y
print(ans)

[[12 14 12]
 [13  8 10]
 [15  9  7]]


In [30]:
import numpy as np

x= np.random.randint(1,10,(3,3))
y= np.random.randint(1,10,(3))
print(x)
print()
print(y)

[[2 9 2]
 [7 9 5]
 [9 3 4]]

[3 8 5]


In [31]:
ans = x-y #for y row is repeated 3 times to do element by element subtraction
ans 

array([[-1,  1, -3],
       [ 4,  1,  0],
       [ 6, -5, -1]])

In [32]:
# a=3 x 2 b=3 x 2
import numpy as np

x= np.random.randint(1,10,(3,2))
y= np.random.randint(1,10,(2,3))
ans = x-y #
ans 

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [33]:
# a=3 x 2 b=3 x 2
import numpy as np

x= np.random.randint(1,10,(3,2))
y= np.random.randint(1,10,(2,3))
y= np.transpose(y)
ans = x-y #
ans 

array([[ 2, -3],
       [-3, -1],
       [ 3, -3]])

In [34]:
# resize
# reshape
# To make them compatible

In [36]:
# Broadcasting Examples

# (3,1) (3,3) -> (3,3) (3,3)
# broadcasted first column to 3 columns

# (1,3) (3,1) -> (3,3) (3,3)
# broadcasted first column to 3 columns and broadcasted first row to 3 rows

# (1,3) (1,1) -> (1,3) (1,3)


In [37]:
# Create killed+wounded colun in 2017 attacks

In [13]:
import csv
import numpy as np

killed=[]
wounded=[]
country=[]

with open('year2017-7767.csv','r',encoding='utf-8') as file_obj:
    data = csv.DictReader(file_obj,skipinitialspace=True)
    data_list = list(data)
    for row in data_list:
        killed.append(row['Killed'])
        wounded.append(row['Wounded'])
        country.append(row['Country'])
# currently we have some '0.0', first float then int
# some have '' cant convert into float

np_killed= np.array(killed) #str
np_wounded= np.array(wounded) #str


np_killed[np_killed=='']='0.0'
np_wounded[np_wounded=='']='0.0'

np_killed= np.array(np_killed,dtype= float)
np_killed= np.array(np_killed,dtype= int)

np_wounded= np.array(np_wounded,dtype= float)
np_wounded= np.array(np_wounded,dtype= int)


killed_wounded = np_killed+np_wounded
print(np_killed)
print(np_wounded)
print(killed_wounded)

[0 2 7 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 2 7 ... 0 0 0]


In [16]:
# What if i want k+w for india
np_country = np.array(country)
bool_arr= np_country=='India'
ans=killed_wounded[bool_arr]
print(np.sum(ans))
print(np.sum(killed_wounded))


1167
51372
